// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-reviews.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEYS or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-reviews.ts
var search_reviews_default = defineTool({
  name: "search_reviews",
  title: "Search mie ayam reviews",
  description: "Search reviews of mie ayam outlets on Mie Ayam Ranger. Filter by city, product type (kuah/goreng), and minimum overall score. Returns compact list ordered by score.",
  inputSchema: {
    city: z.string().optional().describe("Filter by city (partial, case-insensitive match)."),
    product_type: z.enum(["kuah", "goreng"]).optional().describe("Filter by product type: kuah (soup) or goreng (fried)."),
    min_score: z.number().min(0).max(10).optional().describe("Minimum overall_score (0-10)."),
    max_price: z.number().int().positive().optional().describe("Maximum price in IDR."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max number of results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city: city2, product_type, min_score, max_price, limit }, ctx) => {
    let sb;
    try {
      sb = supabaseForUser(ctx);
    } catch (e) {
      return { content: [{ type: "text", text: `Konfigurasi server bermasalah: ${e.message}` }], isError: true };
    }
    let q = sb.from("reviews").select("slug, outlet_name, city, address, product_type, price, overall_score, notes").eq("is_published", true).order("overall_score", { ascending: false }).limit(limit);
    if (city2) q = q.ilike("city", `%${city2}%`);
    if (product_type) q = q.eq("product_type", product_type);
    if (typeof min_score === "number") q = q.gte("overall_score", min_score);
    if (typeof max_price === "number") q = q.lte("price", max_price);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-review.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_review_default = defineTool2({
  name: "get_review",
  title: "Get review detail by slug",
  description: "Fetch full review detail for a single mie ayam outlet by its URL slug, including all scoring parameters (kuah, goreng, mie, ayam, fasilitas, service) and toppings.",
  inputSchema: {
    slug: z2.string().min(1).describe("The review URL slug, e.g. 'mie-ayam-pak-saryono'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    const { data, error } = await supabaseForUser(ctx).from("reviews").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: `No review found for slug '${slug}'.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { review: data }
    };
  }
});

// src/lib/mcp/tools/list-wishlist.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_wishlist_default = defineTool3({
  name: "list_wishlist",
  title: "List wishlist entries",
  description: "List community-submitted wishlist entries (mie ayam outlets pending review). Filter by status. Pending/rejected entries require admin privileges via RLS.",
  inputSchema: {
    status: z3.enum(["pending", "approved", "rejected"]).default("approved").describe("Wishlist status filter."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    const { data, error } = await supabaseForUser(ctx).from("wishlist_entries").select("id, place_name, location, notes, status, created_at").eq("status", status).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-wishlist.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
var submit_wishlist_default = defineTool4({
  name: "submit_wishlist",
  title: "Submit a mie ayam outlet to the wishlist",
  description: "Submit a new mie ayam outlet recommendation to the wishlist. Entry starts with status 'pending' and needs admin approval before appearing publicly.",
  inputSchema: {
    place_name: z4.string().min(1).describe("Name of the mie ayam outlet."),
    location: z4.string().min(1).describe("City / address / area of the outlet."),
    notes: z4.string().optional().describe("Why this outlet is worth reviewing (optional).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ place_name, location, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("wishlist_entries").insert({ place_name, location, notes: notes ?? null, status: "pending" }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Wishlist entry submitted (pending review). ID: ${data.id}` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/moderate-wishlist.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
var moderate_wishlist_default = defineTool5({
  name: "moderate_wishlist",
  title: "Approve or reject a wishlist entry (admin)",
  description: "Set the status of a wishlist entry to 'approved' or 'rejected'. Requires admin privileges; RLS will reject non-admin callers.",
  inputSchema: {
    id: z5.string().uuid().describe("Wishlist entry ID."),
    status: z5.enum(["approved", "rejected"]).describe("New status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("wishlist_entries").update({ status }).eq("id", id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Wishlist entry ${id} set to '${status}'.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/get-review-template.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
var TEMPLATE = `Template review Mie Ayam Ranger (nilai 0-10, boleh desimal):
WAJIB: outlet_name, address, city, price (Rupiah penuh, mis. 12000), product_type (kuah/goreng)
Semua tipe: mie_tekstur, ayam_bumbu, ayam_potongan, fasilitas_kebersihan, fasilitas_alat_makan, fasilitas_tempat
Kuah: kuah_kekentalan, kuah_keseimbangan, kuah_kaldu, kuah_aroma, kuah_kejernihan
Goreng: goreng_keseimbangan_minyak, goreng_bumbu_tumisan, goreng_aroma_tumisan
Opsional: visit_date (YYYY-MM-DD), service_durasi (menit), mie_tipe, google_map_url, complexity (-5..5), sweetness (-5..5), notes, toppings
Topping: ceker, bakso, ekstra_ayam, ekstra_sawi, balungan, tetelan, mie_jumbo, jenis_mie, pangsit_basah, pangsit_kering, dimsum, variasi_bumbu, bawang_daun, jamur, tauge, acar, kerupuk

Alur: kumpulkan nilai -> preview_score -> create_review (draft, request_id unik) -> tampilkan ringkasan -> user setuju -> publish_review. Batal -> discard_draft. Foto chat -> attach_review_image dengan image_base64.

Contoh pesan: "Mie Ayam Pak Kumis, Jl. Slamet Riyadi 10, Solo, 12rb, kuah. Mie 8, bumbu ayam 7.5, potongan 7, kental 7, seimbang 8, kaldu 8, aroma 7.5, jernih 7, bersih 7, alat makan 7, tempat 6. Saji 6 menit. Topping bakso, pangsit kering."`;
var get_review_template_default = defineTool6({
  name: "get_review_template",
  title: "Get review input template",
  description: "Return the list of review fields, which are required per product type, available toppings, and an example message.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({ content: [{ type: "text", text: TEMPLATE }] })
});

// src/lib/mcp/tools/preview-score.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/review-fields.ts
import { z as z6 } from "npm:zod@^4.4.3";
var score = z6.number().min(0).max(10);
var reviewFieldShape = {
  outlet_name: z6.string().trim().min(2).max(200).describe("Nama warung/outlet."),
  address: z6.string().trim().min(3).max(500).describe("Alamat lengkap."),
  city: z6.string().trim().min(2).max(100).describe("Kota."),
  visit_date: z6.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Tanggal kunjungan YYYY-MM-DD (default: hari ini)."),
  price: z6.number().int().min(1e3).max(1e6).describe("Harga dalam Rupiah, minimal 1000 (mis. 12000, bukan 12)."),
  product_type: z6.enum(["kuah", "goreng"]).describe("kuah atau goreng."),
  google_map_url: z6.string().url().max(2048).optional(),
  mie_tipe: z6.string().max(100).optional().describe("Jenis mie, mis. 'mie kecil', 'mie pipih'."),
  mie_tekstur: score.optional(),
  ayam_bumbu: score.optional(),
  ayam_potongan: score.optional(),
  kuah_kekentalan: score.optional().describe("Wajib untuk kuah."),
  kuah_keseimbangan: score.optional().describe("Wajib untuk kuah."),
  kuah_kaldu: score.optional().describe("Wajib untuk kuah."),
  kuah_aroma: score.optional().describe("Wajib untuk kuah."),
  kuah_kejernihan: score.optional().describe("Wajib untuk kuah."),
  goreng_keseimbangan_minyak: score.optional().describe("Wajib untuk goreng."),
  goreng_bumbu_tumisan: score.optional().describe("Wajib untuk goreng."),
  goreng_aroma_tumisan: score.optional().describe("Wajib untuk goreng."),
  fasilitas_kebersihan: score.optional(),
  fasilitas_alat_makan: score.optional(),
  fasilitas_tempat: score.optional(),
  service_durasi: z6.number().min(0).max(120).optional().describe("Lama penyajian dalam menit."),
  complexity: z6.number().int().min(-5).max(5).optional().describe("Kompleksitas rasa -5..+5."),
  sweetness: z6.number().int().min(-5).max(5).optional().describe("Asin(-5) .. manis(+5)."),
  notes: z6.string().max(1e4).optional().describe("Catatan review (markdown)."),
  toppings: z6.array(
    z6.enum([
      "ceker",
      "bakso",
      "ekstra_ayam",
      "ekstra_sawi",
      "balungan",
      "tetelan",
      "mie_jumbo",
      "jenis_mie",
      "pangsit_basah",
      "pangsit_kering",
      "dimsum",
      "variasi_bumbu",
      "bawang_daun",
      "jamur",
      "tauge",
      "acar",
      "kerupuk"
    ])
  ).optional().describe("Daftar topping yang tersedia.")
};
var TOPPINGS = [
  "ceker",
  "bakso",
  "ekstra_ayam",
  "ekstra_sawi",
  "balungan",
  "tetelan",
  "mie_jumbo",
  "jenis_mie",
  "pangsit_basah",
  "pangsit_kering",
  "dimsum",
  "variasi_bumbu",
  "bawang_daun",
  "jamur",
  "tauge",
  "acar",
  "kerupuk"
];
var REQUIRED_COMMON = ["mie_tekstur", "ayam_bumbu", "ayam_potongan", "fasilitas_kebersihan", "fasilitas_alat_makan", "fasilitas_tempat"];
var REQUIRED_KUAH = ["kuah_kekentalan", "kuah_keseimbangan", "kuah_kaldu", "kuah_aroma", "kuah_kejernihan"];
var REQUIRED_GORENG = ["goreng_keseimbangan_minyak", "goreng_bumbu_tumisan", "goreng_aroma_tumisan"];
function missingScoreFields(input, type) {
  const req = [...REQUIRED_COMMON, ...type === "kuah" ? REQUIRED_KUAH : REQUIRED_GORENG];
  return req.filter((k) => typeof input[k] !== "number");
}
function toReviewRow(input, allToppings) {
  const { toppings, ...rest } = input;
  const row = {};
  for (const [k, v] of Object.entries(rest)) if (v !== void 0) row[k] = v;
  if (toppings !== void 0 || allToppings) {
    const set = new Set(toppings ?? []);
    for (const t of TOPPINGS) row[`topping_${t}`] = set.has(t);
  }
  return row;
}
function scoreRpcArgs(r) {
  const n = (k) => typeof r[k] === "number" ? r[k] : 0;
  const b = (t) => r[`topping_${t}`] === true;
  return {
    p_product_type: String(r.product_type),
    p_price: n("price"),
    p_mie_tekstur: n("mie_tekstur"),
    p_ayam_bumbu: n("ayam_bumbu"),
    p_ayam_potongan: n("ayam_potongan"),
    p_kuah_kekentalan: n("kuah_kekentalan"),
    p_kuah_keseimbangan: n("kuah_keseimbangan"),
    p_kuah_kaldu: n("kuah_kaldu"),
    p_kuah_aroma: n("kuah_aroma"),
    p_kuah_kejernihan: n("kuah_kejernihan"),
    p_goreng_keseimbangan_minyak: n("goreng_keseimbangan_minyak"),
    p_goreng_bumbu_tumisan: n("goreng_bumbu_tumisan"),
    p_goreng_aroma_tumisan: n("goreng_aroma_tumisan"),
    p_fasilitas_kebersihan: n("fasilitas_kebersihan"),
    p_fasilitas_alat_makan: n("fasilitas_alat_makan"),
    p_fasilitas_tempat: n("fasilitas_tempat"),
    p_service_durasi: n("service_durasi"),
    p_topping_ceker: b("ceker"),
    p_topping_bakso: b("bakso"),
    p_topping_ekstra_ayam: b("ekstra_ayam"),
    p_topping_ekstra_sawi: b("ekstra_sawi"),
    p_topping_balungan: b("balungan"),
    p_topping_tetelan: b("tetelan"),
    p_topping_mie_jumbo: b("mie_jumbo"),
    p_topping_jenis_mie: b("jenis_mie"),
    p_topping_pangsit_basah: b("pangsit_basah"),
    p_topping_pangsit_kering: b("pangsit_kering"),
    p_topping_dimsum: b("dimsum"),
    p_topping_variasi_bumbu: b("variasi_bumbu"),
    p_topping_bawang_daun: b("bawang_daun"),
    p_topping_jamur: b("jamur"),
    p_topping_tauge: b("tauge"),
    p_topping_acar: b("acar"),
    p_topping_kerupuk: b("kerupuk")
  };
}
var SITE_URL = "https://mieayamranger.web.id";
var reviewLink = (slug) => slug ? `${SITE_URL}/reviews/${slug}` : null;
var notAuth = { content: [{ type: "text", text: "Not authenticated" }], isError: true };
var errText = (text) => ({ content: [{ type: "text", text }], isError: true });
async function requireAdmin(sb, userId) {
  if (!userId) return "Tidak terautentikasi.";
  const { data, error } = await sb.rpc("is_admin", { _user_id: userId });
  if (error) return `Gagal cek izin admin: ${error.message}`;
  return data === true ? null : "Izin ditolak: akun ini bukan admin Mie Ayam Ranger.";
}

// src/lib/mcp/tools/preview-score.ts
var { outlet_name, address, city, ...scoreShape } = reviewFieldShape;
var preview_score_default = defineTool7({
  name: "preview_score",
  title: "Preview review score",
  description: "Calculate the Scoring v2 overall score for review inputs without saving anything. Use before create_review to confirm with the user.",
  inputSchema: scoreShape,
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuth;
    const row = toReviewRow(input, true);
    const missing = missingScoreFields(row, input.product_type);
    const { data, error } = await supabaseForUser(ctx).rpc("calculate_review_overall_score_v2", scoreRpcArgs(row));
    if (error) return errText(error.message);
    const score2 = Math.round(Number(data) * 100) / 100;
    const warn = missing.length ? ` Nilai belum lengkap (dihitung 0): ${missing.join(", ")}.` : "";
    return {
      content: [{ type: "text", text: `Perkiraan skor akhir: ${score2}/10.${warn}` }],
      structuredContent: { score: score2, missing_fields: missing }
    };
  }
});

// src/lib/mcp/tools/create-review.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@^4.4.3";
var create_review_default = defineTool8({
  name: "create_review",
  title: "Create a review draft (admin)",
  description: "Save a new mie ayam review as an unpublished DRAFT. Admin only. Pass a unique request_id per review so retries never create duplicates. Show the returned summary to the user and call publish_review only after explicit approval.",
  inputSchema: {
    request_id: z7.string().trim().min(8).max(100).describe("ID unik per review (mis. UUID). Ulangi nilai yang sama saat retry."),
    ...reviewFieldShape
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ request_id, ...input }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuth;
    const sb = supabaseForUser(ctx);
    const denied = await requireAdmin(sb, ctx.getUserId());
    if (denied) return errText(denied);
    const { data: existing } = await sb.from("reviews").select("id, slug, outlet_name, overall_score, is_published").eq("client_request_id", request_id).maybeSingle();
    if (existing) {
      return {
        content: [{ type: "text", text: `Request ini sudah pernah disimpan: "${existing.outlet_name}" (slug ${existing.slug}, ${existing.is_published ? "sudah tayang" : "draft"}, skor ${Number(existing.overall_score).toFixed(2)}). Tidak dibuat ulang.` }],
        structuredContent: { id: existing.id, slug: existing.slug, overall_score: Number(existing.overall_score), is_published: existing.is_published, duplicate: true }
      };
    }
    const row = toReviewRow(input, true);
    const missing = missingScoreFields(row, input.product_type);
    if (missing.length) return errText(`Field wajib belum diisi: ${missing.join(", ")}. Tanyakan ke user lalu coba lagi.`);
    if (!row.visit_date) row.visit_date = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    row.is_published = false;
    row.client_request_id = request_id;
    const { data, error } = await sb.from("reviews").insert(row).select("id, slug, outlet_name, city, price, product_type, overall_score").single();
    if (error) return errText(`Gagal menyimpan draft: ${error.message}${error.details ? ` (${error.details})` : ""}`);
    const summary = `DRAFT tersimpan (belum tayang): "${data.outlet_name}", ${data.city}, Rp${data.price}, ${data.product_type}. Skor: ${Number(data.overall_score).toFixed(2)}/10. Slug: ${data.slug}. Minta persetujuan user, lalu panggil publish_review dengan slug ini; atau discard_draft untuk membatalkan.`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { id: data.id, slug: data.slug, overall_score: Number(data.overall_score), is_published: false, preview_url: reviewLink(data.slug) }
    };
  }
});

// src/lib/mcp/tools/update-review.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z8 } from "npm:zod@^4.4.3";
var partial = Object.fromEntries(
  Object.entries(reviewFieldShape).map(([k, v]) => [k, v.optional()])
);
var update_review_default = defineTool9({
  name: "update_review",
  title: "Update a review (admin)",
  description: "Update selected fields of an existing review by slug. Only provided fields change. If toppings is given it replaces the whole topping list.",
  inputSchema: { slug: z8.string().min(1).describe("Slug review."), ...partial },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, ...fields }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuth;
    const row = toReviewRow(fields, false);
    if (!Object.keys(row).length) return errText("Tidak ada field yang diubah.");
    const { data, error } = await supabaseForUser(ctx).from("reviews").update(row).eq("slug", slug).select("id, slug, outlet_name, overall_score").maybeSingle();
    if (error) return errText(error.message);
    if (!data) return errText(`Review '${slug}' tidak ditemukan atau akun bukan admin.`);
    return {
      content: [{ type: "text", text: `Review "${data.outlet_name}" diperbarui. Skor sekarang: ${Number(data.overall_score).toFixed(2)}/10.` }],
      structuredContent: { id: data.id, slug: data.slug, overall_score: Number(data.overall_score), url: reviewLink(data.slug) }
    };
  }
});

// src/lib/mcp/tools/attach-review-image.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z9 } from "npm:zod@^4.4.3";
var MAX = 8 * 1024 * 1024;
var TIMEOUT_MS = 15e3;
function sniff(b) {
  if (b[0] === 255 && b[1] === 216 && b[2] === 255) return { mime: "image/jpeg", ext: "jpg" };
  if (b[0] === 137 && b[1] === 80 && b[2] === 78 && b[3] === 71) return { mime: "image/png", ext: "png" };
  if (b[0] === 82 && b[1] === 73 && b[2] === 70 && b[3] === 70 && b[8] === 87 && b[9] === 69 && b[10] === 66 && b[11] === 80) return { mime: "image/webp", ext: "webp" };
  return null;
}
function isPrivateHost(host) {
  const h = host.toLowerCase().replace(/^\[|\]$/g, "");
  if (h === "localhost" || h.endsWith(".localhost") || h.endsWith(".local") || h.endsWith(".internal")) return true;
  if (h.includes(":")) return h === "::1" || h.startsWith("fc") || h.startsWith("fd") || h.startsWith("fe80") || h.startsWith("::ffff:");
  const m = h.match(/^(\d+)\.(\d+)\.(\d+)\.(\d+)$/);
  if (!m) return false;
  const [a, b] = [Number(m[1]), Number(m[2])];
  return a === 10 || a === 127 || a === 0 || a === 169 && b === 254 || a === 172 && b >= 16 && b <= 31 || a === 192 && b === 168 || a === 100 && b >= 64 && b <= 127 || a >= 224;
}
async function resolvesPrivate(host) {
  const deno = globalThis.Deno;
  if (!deno?.resolveDns || /^[\d.]+$/.test(host) || host.includes(":")) return false;
  for (const t of ["A", "AAAA"]) {
    try {
      if ((await deno.resolveDns(host, t)).some(isPrivateHost)) return true;
    } catch {
    }
  }
  return false;
}
async function download(url) {
  let u;
  try {
    u = new URL(url);
  } catch {
    return "image_url tidak valid.";
  }
  if (u.protocol !== "https:") return "image_url harus https.";
  if (isPrivateHost(u.hostname) || await resolvesPrivate(u.hostname)) return "image_url menunjuk ke alamat internal; ditolak.";
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(u, { signal: ctrl.signal, redirect: "error" });
    if (!res.ok || !res.body) return `Gagal unduh gambar: HTTP ${res.status}`;
    const len = Number(res.headers.get("content-length") ?? 0);
    if (len > MAX) return "Gambar lebih dari 8 MB.";
    const reader = res.body.getReader();
    const chunks = [];
    let total = 0;
    for (; ; ) {
      const { done, value } = await reader.read();
      if (done) break;
      total += value.byteLength;
      if (total > MAX) {
        await reader.cancel();
        return "Gambar lebih dari 8 MB.";
      }
      chunks.push(value);
    }
    const out = new Uint8Array(total);
    let o = 0;
    for (const c of chunks) {
      out.set(c, o);
      o += c.byteLength;
    }
    return out;
  } catch (e) {
    return e.name === "AbortError" ? "Unduhan gambar melebihi 15 detik." : `Gagal unduh gambar: ${e.message}`;
  } finally {
    clearTimeout(timer);
  }
}
var attach_review_image_default = defineTool10({
  name: "attach_review_image",
  title: "Attach a photo to a review (admin)",
  description: "Add a photo to a review. For Telegram/WhatsApp photos, read the locally saved file and pass it as image_base64 (Telegram file URLs contain the bot token \u2014 never pass them). image_url only for public https images. JPEG/PNG/WebP, max 8 MB.",
  inputSchema: {
    slug: z9.string().min(1),
    image_base64: z9.string().max(12e6).optional().describe("Isi file gambar dalam base64 (boleh dengan prefix data:)."),
    image_url: z9.string().url().optional().describe("URL https publik. Alamat internal ditolak."),
    as_menu: z9.boolean().optional().describe("true = foto menu, bukan galeri.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ slug, image_url, image_base64, as_menu }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuth;
    const sb = supabaseForUser(ctx);
    const denied = await requireAdmin(sb, ctx.getUserId());
    if (denied) return errText(denied);
    let bytes;
    if (image_base64) {
      try {
        bytes = Uint8Array.from(atob(image_base64.replace(/^data:[^,]+,/, "").replace(/\s/g, "")), (c) => c.charCodeAt(0));
      } catch {
        return errText("image_base64 tidak valid.");
      }
      if (bytes.byteLength > MAX) return errText("Gambar lebih dari 8 MB.");
    } else if (image_url) {
      const r = await download(image_url);
      if (typeof r === "string") return errText(r);
      bytes = r;
    } else return errText("Berikan image_base64 atau image_url.");
    const kind = sniff(bytes);
    if (!kind) return errText("File bukan gambar JPEG/PNG/WebP yang valid.");
    const { data: review, error: rErr } = await sb.from("reviews").select("id, image_url, image_urls").eq("slug", slug).maybeSingle();
    if (rErr) return errText(rErr.message);
    if (!review) return errText(`Review '${slug}' tidak ditemukan.`);
    const path = `${review.id}/${Date.now()}.${kind.ext}`;
    const { error: upErr } = await sb.storage.from("review-images").upload(path, bytes, { contentType: kind.mime });
    if (upErr) return errText(`Upload gagal: ${upErr.message}`);
    const publicUrl = sb.storage.from("review-images").getPublicUrl(path).data.publicUrl;
    const patch = as_menu ? { menu_image_url: publicUrl } : { image_urls: [...review.image_urls ?? [], publicUrl], image_url: review.image_url ?? publicUrl };
    const { error: uErr } = await sb.from("reviews").update(patch).eq("id", review.id);
    if (uErr) {
      await sb.storage.from("review-images").remove([path]);
      return errText(`Gagal menyimpan ke review (file dibersihkan): ${uErr.message}`);
    }
    return { content: [{ type: "text", text: `Foto ditambahkan: ${publicUrl}` }], structuredContent: { url: publicUrl } };
  }
});

// src/lib/mcp/tools/publish-review.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z10 } from "npm:zod@^4.4.3";
var publish_review_default = defineTool11({
  name: "publish_review",
  title: "Publish a review draft (admin)",
  description: "Make a draft review public. Only call after the user explicitly approved the summary. Requires confirm=true.",
  inputSchema: {
    slug: z10.string().min(1),
    confirm: z10.literal(true).describe("Harus true, tanda user sudah menyetujui.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuth;
    const sb = supabaseForUser(ctx);
    const denied = await requireAdmin(sb, ctx.getUserId());
    if (denied) return errText(denied);
    const { data, error } = await sb.from("reviews").update({ is_published: true }).eq("slug", slug).select("slug, outlet_name, overall_score").maybeSingle();
    if (error) return errText(error.message);
    if (!data) return errText(`Review '${slug}' tidak ditemukan.`);
    const url = reviewLink(data.slug);
    return {
      content: [{ type: "text", text: `"${data.outlet_name}" sudah tayang. Skor ${Number(data.overall_score).toFixed(2)}/10. ${url}` }],
      structuredContent: { slug: data.slug, url, overall_score: Number(data.overall_score) }
    };
  }
});

// src/lib/mcp/tools/discard-draft.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z11 } from "npm:zod@^4.4.3";
var discard_draft_default = defineTool12({
  name: "discard_draft",
  title: "Discard an unpublished draft (admin)",
  description: "Delete a review draft that was never published, plus its uploaded photos. Published reviews are never deleted by this tool.",
  inputSchema: { slug: z11.string().min(1) },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuth;
    const sb = supabaseForUser(ctx);
    const denied = await requireAdmin(sb, ctx.getUserId());
    if (denied) return errText(denied);
    const { data: review } = await sb.from("reviews").select("id, is_published").eq("slug", slug).maybeSingle();
    if (!review) return errText(`Review '${slug}' tidak ditemukan.`);
    if (review.is_published) return errText("Ditolak: review ini sudah tayang. discard_draft hanya untuk draft.");
    const { data: files } = await sb.storage.from("review-images").list(review.id);
    if (files?.length) await sb.storage.from("review-images").remove(files.map((f) => `${review.id}/${f.name}`));
    const { error } = await sb.from("reviews").delete().eq("id", review.id).eq("is_published", false);
    if (error) return errText(error.message);
    return { content: [{ type: "text", text: `Draft '${slug}' dibatalkan dan dihapus.` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kqsqocrtaybbkpigvwjy";
var mcp_default = defineMcp({
  name: "mieayam-ranger-review",
  title: "mieayam-ranger-review",
  version: "0.3.0",
  instructions: "Tools for Mie Ayam Ranger \u2014 Indonesian mie ayam outlet reviews. Explore with `search_reviews` and `get_review`. To publish a review from chat: call `get_review_template`, collect missing scores from the user, call `preview_score`, confirm with the user, then `create_review` (saves an unpublished draft; reuse the same request_id on retry), show the summary and ask for explicit approval, then `publish_review` (or `discard_draft` to cancel); add photos with `attach_review_image` (pass chat photos as base64); fix mistakes with `update_review`. Writing reviews requires an admin account. Wishlist: `list_wishlist`, `submit_wishlist`, `moderate_wishlist` (admin).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_reviews_default,
    get_review_default,
    list_wishlist_default,
    submit_wishlist_default,
    moderate_wishlist_default,
    get_review_template_default,
    preview_score_default,
    create_review_default,
    publish_review_default,
    discard_draft_default,
    update_review_default,
    attach_review_image_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
