// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-reviews.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEYS or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-reviews.ts
var search_reviews_default = defineTool({
  name: "search_reviews",
  title: "Search mie ayam reviews",
  description: "Search reviews of mie ayam outlets on Mie Ayam Ranger. Filter by city, product type (kuah/goreng), and minimum overall score. Returns compact list ordered by score.",
  inputSchema: {
    city: z.string().optional().describe("Filter by city (partial, case-insensitive match)."),
    product_type: z.enum(["kuah", "goreng"]).optional().describe("Filter by product type: kuah (soup) or goreng (fried)."),
    min_score: z.number().min(0).max(10).optional().describe("Minimum overall_score (0-10)."),
    max_price: z.number().int().positive().optional().describe("Maximum price in IDR."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max number of results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city: city2, product_type, min_score, max_price, limit }, ctx) => {
    let q = supabaseForUser(ctx).from("reviews").select("slug, outlet_name, city, address, product_type, price, overall_score, notes").order("overall_score", { ascending: false }).limit(limit);
    if (city2) q = q.ilike("city", `%${city2}%`);
    if (product_type) q = q.eq("product_type", product_type);
    if (typeof min_score === "number") q = q.gte("overall_score", min_score);
    if (typeof max_price === "number") q = q.lte("price", max_price);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-review.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_review_default = defineTool2({
  name: "get_review",
  title: "Get review detail by slug",
  description: "Fetch full review detail for a single mie ayam outlet by its URL slug, including all scoring parameters (kuah, goreng, mie, ayam, fasilitas, service) and toppings.",
  inputSchema: {
    slug: z2.string().min(1).describe("The review URL slug, e.g. 'mie-ayam-pak-saryono'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    const { data, error } = await supabaseForUser(ctx).from("reviews").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: `No review found for slug '${slug}'.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { review: data }
    };
  }
});

// src/lib/mcp/tools/list-wishlist.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_wishlist_default = defineTool3({
  name: "list_wishlist",
  title: "List wishlist entries",
  description: "List community-submitted wishlist entries (mie ayam outlets pending review). Filter by status. Pending/rejected entries require admin privileges via RLS.",
  inputSchema: {
    status: z3.enum(["pending", "approved", "rejected"]).default("approved").describe("Wishlist status filter."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    const { data, error } = await supabaseForUser(ctx).from("wishlist_entries").select("id, place_name, location, notes, status, created_at").eq("status", status).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-wishlist.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
var submit_wishlist_default = defineTool4({
  name: "submit_wishlist",
  title: "Submit a mie ayam outlet to the wishlist",
  description: "Submit a new mie ayam outlet recommendation to the wishlist. Entry starts with status 'pending' and needs admin approval before appearing publicly.",
  inputSchema: {
    place_name: z4.string().min(1).describe("Name of the mie ayam outlet."),
    location: z4.string().min(1).describe("City / address / area of the outlet."),
    notes: z4.string().optional().describe("Why this outlet is worth reviewing (optional).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ place_name, location, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("wishlist_entries").insert({ place_name, location, notes: notes ?? null, status: "pending" }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Wishlist entry submitted (pending review). ID: ${data.id}` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/moderate-wishlist.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
var moderate_wishlist_default = defineTool5({
  name: "moderate_wishlist",
  title: "Approve or reject a wishlist entry (admin)",
  description: "Set the status of a wishlist entry to 'approved' or 'rejected'. Requires admin privileges; RLS will reject non-admin callers.",
  inputSchema: {
    id: z5.string().uuid().describe("Wishlist entry ID."),
    status: z5.enum(["approved", "rejected"]).describe("New status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("wishlist_entries").update({ status }).eq("id", id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Wishlist entry ${id} set to '${status}'.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/get-review-template.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
var TEMPLATE = `Template review Mie Ayam Ranger (nilai 0-10, boleh desimal):
WAJIB: outlet_name, address, city, price (Rupiah penuh, mis. 12000), product_type (kuah/goreng)
Semua tipe: mie_tekstur, ayam_bumbu, ayam_potongan, fasilitas_kebersihan, fasilitas_alat_makan, fasilitas_tempat
Kuah: kuah_kekentalan, kuah_keseimbangan, kuah_kaldu, kuah_aroma, kuah_kejernihan
Goreng: goreng_keseimbangan_minyak, goreng_bumbu_tumisan, goreng_aroma_tumisan
Opsional: visit_date (YYYY-MM-DD), service_durasi (menit), mie_tipe, google_map_url, complexity (-5..5), sweetness (-5..5), notes, toppings
Topping: ceker, bakso, ekstra_ayam, ekstra_sawi, balungan, tetelan, mie_jumbo, jenis_mie, pangsit_basah, pangsit_kering, dimsum, variasi_bumbu, bawang_daun, jamur, tauge, acar, kerupuk

Alur: kumpulkan nilai -> preview_score -> konfirmasi user -> create_review -> attach_review_image untuk foto.

Contoh pesan: "Mie Ayam Pak Kumis, Jl. Slamet Riyadi 10, Solo, 12rb, kuah. Mie 8, bumbu ayam 7.5, potongan 7, kental 7, seimbang 8, kaldu 8, aroma 7.5, jernih 7, bersih 7, alat makan 7, tempat 6. Saji 6 menit. Topping bakso, pangsit kering."`;
var get_review_template_default = defineTool6({
  name: "get_review_template",
  title: "Get review input template",
  description: "Return the list of review fields, which are required per product type, available toppings, and an example message.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({ content: [{ type: "text", text: TEMPLATE }] })
});

// src/lib/mcp/tools/preview-score.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/review-fields.ts
import { z as z6 } from "npm:zod@^4.4.3";
var score = z6.number().min(0).max(10);
var reviewFieldShape = {
  outlet_name: z6.string().trim().min(2).max(200).describe("Nama warung/outlet."),
  address: z6.string().trim().min(3).max(500).describe("Alamat lengkap."),
  city: z6.string().trim().min(2).max(100).describe("Kota."),
  visit_date: z6.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Tanggal kunjungan YYYY-MM-DD (default: hari ini)."),
  price: z6.number().int().min(1e3).max(1e6).describe("Harga dalam Rupiah, minimal 1000 (mis. 12000, bukan 12)."),
  product_type: z6.enum(["kuah", "goreng"]).describe("kuah atau goreng."),
  google_map_url: z6.string().url().max(2048).optional(),
  mie_tipe: z6.string().max(100).optional().describe("Jenis mie, mis. 'mie kecil', 'mie pipih'."),
  mie_tekstur: score.optional(),
  ayam_bumbu: score.optional(),
  ayam_potongan: score.optional(),
  kuah_kekentalan: score.optional().describe("Wajib untuk kuah."),
  kuah_keseimbangan: score.optional().describe("Wajib untuk kuah."),
  kuah_kaldu: score.optional().describe("Wajib untuk kuah."),
  kuah_aroma: score.optional().describe("Wajib untuk kuah."),
  kuah_kejernihan: score.optional().describe("Wajib untuk kuah."),
  goreng_keseimbangan_minyak: score.optional().describe("Wajib untuk goreng."),
  goreng_bumbu_tumisan: score.optional().describe("Wajib untuk goreng."),
  goreng_aroma_tumisan: score.optional().describe("Wajib untuk goreng."),
  fasilitas_kebersihan: score.optional(),
  fasilitas_alat_makan: score.optional(),
  fasilitas_tempat: score.optional(),
  service_durasi: z6.number().min(0).max(120).optional().describe("Lama penyajian dalam menit."),
  complexity: z6.number().int().min(-5).max(5).optional().describe("Kompleksitas rasa -5..+5."),
  sweetness: z6.number().int().min(-5).max(5).optional().describe("Asin(-5) .. manis(+5)."),
  notes: z6.string().max(1e4).optional().describe("Catatan review (markdown)."),
  toppings: z6.array(
    z6.enum([
      "ceker",
      "bakso",
      "ekstra_ayam",
      "ekstra_sawi",
      "balungan",
      "tetelan",
      "mie_jumbo",
      "jenis_mie",
      "pangsit_basah",
      "pangsit_kering",
      "dimsum",
      "variasi_bumbu",
      "bawang_daun",
      "jamur",
      "tauge",
      "acar",
      "kerupuk"
    ])
  ).optional().describe("Daftar topping yang tersedia.")
};
var TOPPINGS = [
  "ceker",
  "bakso",
  "ekstra_ayam",
  "ekstra_sawi",
  "balungan",
  "tetelan",
  "mie_jumbo",
  "jenis_mie",
  "pangsit_basah",
  "pangsit_kering",
  "dimsum",
  "variasi_bumbu",
  "bawang_daun",
  "jamur",
  "tauge",
  "acar",
  "kerupuk"
];
var REQUIRED_COMMON = ["mie_tekstur", "ayam_bumbu", "ayam_potongan", "fasilitas_kebersihan", "fasilitas_alat_makan", "fasilitas_tempat"];
var REQUIRED_KUAH = ["kuah_kekentalan", "kuah_keseimbangan", "kuah_kaldu", "kuah_aroma", "kuah_kejernihan"];
var REQUIRED_GORENG = ["goreng_keseimbangan_minyak", "goreng_bumbu_tumisan", "goreng_aroma_tumisan"];
function missingScoreFields(input, type) {
  const req = [...REQUIRED_COMMON, ...type === "kuah" ? REQUIRED_KUAH : REQUIRED_GORENG];
  return req.filter((k) => typeof input[k] !== "number");
}
function toReviewRow(input, allToppings) {
  const { toppings, ...rest } = input;
  const row = {};
  for (const [k, v] of Object.entries(rest)) if (v !== void 0) row[k] = v;
  if (toppings !== void 0 || allToppings) {
    const set = new Set(toppings ?? []);
    for (const t of TOPPINGS) row[`topping_${t}`] = set.has(t);
  }
  return row;
}
function scoreRpcArgs(r) {
  const n = (k) => typeof r[k] === "number" ? r[k] : 0;
  const b = (t) => r[`topping_${t}`] === true;
  return {
    p_product_type: String(r.product_type),
    p_price: n("price"),
    p_mie_tekstur: n("mie_tekstur"),
    p_ayam_bumbu: n("ayam_bumbu"),
    p_ayam_potongan: n("ayam_potongan"),
    p_kuah_kekentalan: n("kuah_kekentalan"),
    p_kuah_keseimbangan: n("kuah_keseimbangan"),
    p_kuah_kaldu: n("kuah_kaldu"),
    p_kuah_aroma: n("kuah_aroma"),
    p_kuah_kejernihan: n("kuah_kejernihan"),
    p_goreng_keseimbangan_minyak: n("goreng_keseimbangan_minyak"),
    p_goreng_bumbu_tumisan: n("goreng_bumbu_tumisan"),
    p_goreng_aroma_tumisan: n("goreng_aroma_tumisan"),
    p_fasilitas_kebersihan: n("fasilitas_kebersihan"),
    p_fasilitas_alat_makan: n("fasilitas_alat_makan"),
    p_fasilitas_tempat: n("fasilitas_tempat"),
    p_service_durasi: n("service_durasi"),
    p_topping_ceker: b("ceker"),
    p_topping_bakso: b("bakso"),
    p_topping_ekstra_ayam: b("ekstra_ayam"),
    p_topping_ekstra_sawi: b("ekstra_sawi"),
    p_topping_balungan: b("balungan"),
    p_topping_tetelan: b("tetelan"),
    p_topping_mie_jumbo: b("mie_jumbo"),
    p_topping_jenis_mie: b("jenis_mie"),
    p_topping_pangsit_basah: b("pangsit_basah"),
    p_topping_pangsit_kering: b("pangsit_kering"),
    p_topping_dimsum: b("dimsum"),
    p_topping_variasi_bumbu: b("variasi_bumbu"),
    p_topping_bawang_daun: b("bawang_daun"),
    p_topping_jamur: b("jamur"),
    p_topping_tauge: b("tauge"),
    p_topping_acar: b("acar"),
    p_topping_kerupuk: b("kerupuk")
  };
}
var SITE_URL = "https://mieayamranger.web.id";
var reviewLink = (slug) => slug ? `${SITE_URL}/reviews/${slug}` : null;
var notAuth = { content: [{ type: "text", text: "Not authenticated" }], isError: true };
var errText = (text) => ({ content: [{ type: "text", text }], isError: true });

// src/lib/mcp/tools/preview-score.ts
var { outlet_name, address, city, ...scoreShape } = reviewFieldShape;
var preview_score_default = defineTool7({
  name: "preview_score",
  title: "Preview review score",
  description: "Calculate the Scoring v2 overall score for review inputs without saving anything. Use before create_review to confirm with the user.",
  inputSchema: scoreShape,
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuth;
    const row = toReviewRow(input, true);
    const missing = missingScoreFields(row, input.product_type);
    const { data, error } = await supabaseForUser(ctx).rpc("calculate_review_overall_score_v2", scoreRpcArgs(row));
    if (error) return errText(error.message);
    const score2 = Math.round(Number(data) * 100) / 100;
    const warn = missing.length ? ` Nilai belum lengkap (dihitung 0): ${missing.join(", ")}.` : "";
    return {
      content: [{ type: "text", text: `Perkiraan skor akhir: ${score2}/10.${warn}` }],
      structuredContent: { score: score2, missing_fields: missing }
    };
  }
});

// src/lib/mcp/tools/create-review.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
var create_review_default = defineTool8({
  name: "create_review",
  title: "Create a mie ayam review (admin)",
  description: "Publish a new mie ayam review. Admin only. All flavor/facility scores for the chosen product type are required. Returns the final score and review link.",
  inputSchema: reviewFieldShape,
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuth;
    const row = toReviewRow(input, true);
    const missing = missingScoreFields(row, input.product_type);
    if (missing.length) return errText(`Nilai wajib belum diisi: ${missing.join(", ")}. Tanyakan ke user lalu coba lagi.`);
    if (!row.visit_date) row.visit_date = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser(ctx).from("reviews").insert(row).select("id, slug, outlet_name, overall_score").single();
    if (error) return errText(`Gagal menyimpan (pastikan akun admin): ${error.message}`);
    const link = reviewLink(data.slug);
    return {
      content: [{ type: "text", text: `Review "${data.outlet_name}" tersimpan. Skor: ${Number(data.overall_score).toFixed(2)}/10. Slug: ${data.slug}. ${link ?? ""}` }],
      structuredContent: { id: data.id, slug: data.slug, overall_score: Number(data.overall_score), url: link }
    };
  }
});

// src/lib/mcp/tools/update-review.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@^4.4.3";
var partial = Object.fromEntries(
  Object.entries(reviewFieldShape).map(([k, v]) => [k, v.optional()])
);
var update_review_default = defineTool9({
  name: "update_review",
  title: "Update a review (admin)",
  description: "Update selected fields of an existing review by slug. Only provided fields change. If toppings is given it replaces the whole topping list.",
  inputSchema: { slug: z7.string().min(1).describe("Slug review."), ...partial },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, ...fields }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuth;
    const row = toReviewRow(fields, false);
    if (!Object.keys(row).length) return errText("Tidak ada field yang diubah.");
    const { data, error } = await supabaseForUser(ctx).from("reviews").update(row).eq("slug", slug).select("id, slug, outlet_name, overall_score").maybeSingle();
    if (error) return errText(error.message);
    if (!data) return errText(`Review '${slug}' tidak ditemukan atau akun bukan admin.`);
    return {
      content: [{ type: "text", text: `Review "${data.outlet_name}" diperbarui. Skor sekarang: ${Number(data.overall_score).toFixed(2)}/10.` }],
      structuredContent: { id: data.id, slug: data.slug, overall_score: Number(data.overall_score), url: reviewLink(data.slug) }
    };
  }
});

// src/lib/mcp/tools/attach-review-image.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z8 } from "npm:zod@^4.4.3";
var MAX = 8 * 1024 * 1024;
var EXT = { "image/jpeg": "jpg", "image/png": "png", "image/webp": "webp", "image/gif": "gif" };
var attach_review_image_default = defineTool10({
  name: "attach_review_image",
  title: "Attach a photo to a review (admin)",
  description: "Upload a photo (public image URL or base64) and add it to a review's gallery. Set as_menu=true for a menu photo. Max 8 MB, jpeg/png/webp.",
  inputSchema: {
    slug: z8.string().min(1),
    image_url: z8.string().url().optional().describe("URL gambar yang bisa diunduh."),
    image_base64: z8.string().optional().describe("Isi gambar base64 (tanpa prefix data:)."),
    mime_type: z8.enum(["image/jpeg", "image/png", "image/webp", "image/gif"]).optional().describe("Wajib jika memakai base64."),
    as_menu: z8.boolean().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ slug, image_url, image_base64, mime_type, as_menu }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuth;
    let bytes;
    let mime;
    if (image_url) {
      const res = await fetch(image_url);
      if (!res.ok) return errText(`Gagal unduh gambar: ${res.status}`);
      mime = (res.headers.get("content-type") ?? "").split(";")[0];
      bytes = new Uint8Array(await res.arrayBuffer());
    } else if (image_base64 && mime_type) {
      mime = mime_type;
      bytes = Uint8Array.from(atob(image_base64.replace(/^data:[^,]+,/, "")), (c) => c.charCodeAt(0));
    } else return errText("Berikan image_url, atau image_base64 + mime_type.");
    if (!EXT[mime]) return errText(`Tipe file tidak didukung: ${mime || "unknown"}`);
    if (bytes.byteLength > MAX) return errText("Gambar lebih dari 8 MB.");
    const sb = supabaseForUser(ctx);
    const { data: review, error: rErr } = await sb.from("reviews").select("id, image_url, image_urls").eq("slug", slug).maybeSingle();
    if (rErr) return errText(rErr.message);
    if (!review) return errText(`Review '${slug}' tidak ditemukan.`);
    const path = `${review.id}/${Date.now()}.${EXT[mime]}`;
    const { error: upErr } = await sb.storage.from("review-images").upload(path, bytes, { contentType: mime });
    if (upErr) return errText(`Upload gagal (akun admin?): ${upErr.message}`);
    const publicUrl = sb.storage.from("review-images").getPublicUrl(path).data.publicUrl;
    const patch = as_menu ? { menu_image_url: publicUrl } : { image_urls: [...review.image_urls ?? [], publicUrl], image_url: review.image_url ?? publicUrl };
    const { error: uErr } = await sb.from("reviews").update(patch).eq("id", review.id);
    if (uErr) return errText(uErr.message);
    return { content: [{ type: "text", text: `Foto ditambahkan: ${publicUrl}` }], structuredContent: { url: publicUrl } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kqsqocrtaybbkpigvwjy";
var mcp_default = defineMcp({
  name: "mieayam-ranger-review",
  title: "mieayam-ranger-review",
  version: "0.2.0",
  instructions: "Tools for Mie Ayam Ranger \u2014 Indonesian mie ayam outlet reviews. Explore with `search_reviews` and `get_review`. To publish a review from chat: call `get_review_template`, collect missing scores from the user, call `preview_score`, confirm with the user, then `create_review`; add photos with `attach_review_image`; fix mistakes with `update_review`. Writing reviews requires an admin account. Wishlist: `list_wishlist`, `submit_wishlist`, `moderate_wishlist` (admin).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_reviews_default,
    get_review_default,
    list_wishlist_default,
    submit_wishlist_default,
    moderate_wishlist_default,
    get_review_template_default,
    preview_score_default,
    create_review_default,
    update_review_default,
    attach_review_image_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
