// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/search-reviews.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
var env = globalThis.process.env;
function supabaseForUser(ctx) {
  return createClient(env.SUPABASE_URL, env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-reviews.ts
var search_reviews_default = defineTool({
  name: "search_reviews",
  title: "Search mie ayam reviews",
  description: "Search reviews of mie ayam outlets on Mie Ayam Ranger. Filter by city, product type (kuah/goreng), and minimum overall score. Returns compact list ordered by score.",
  inputSchema: {
    city: z.string().optional().describe("Filter by city (partial, case-insensitive match)."),
    product_type: z.enum(["kuah", "goreng"]).optional().describe("Filter by product type: kuah (soup) or goreng (fried)."),
    min_score: z.number().min(0).max(10).optional().describe("Minimum overall_score (0-10)."),
    max_price: z.number().int().positive().optional().describe("Maximum price in IDR."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max number of results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ city, product_type, min_score, max_price, limit }, ctx) => {
    let q = supabaseForUser(ctx).from("reviews").select("slug, outlet_name, city, address, product_type, price, overall_score, notes").order("overall_score", { ascending: false }).limit(limit);
    if (city) q = q.ilike("city", `%${city}%`);
    if (product_type) q = q.eq("product_type", product_type);
    if (typeof min_score === "number") q = q.gte("overall_score", min_score);
    if (typeof max_price === "number") q = q.lte("price", max_price);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-review.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_review_default = defineTool2({
  name: "get_review",
  title: "Get review detail by slug",
  description: "Fetch full review detail for a single mie ayam outlet by its URL slug, including all scoring parameters (kuah, goreng, mie, ayam, fasilitas, service) and toppings.",
  inputSchema: {
    slug: z2.string().min(1).describe("The review URL slug, e.g. 'mie-ayam-pak-saryono'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    const { data, error } = await supabaseForUser(ctx).from("reviews").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: `No review found for slug '${slug}'.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { review: data }
    };
  }
});

// src/lib/mcp/tools/list-wishlist.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_wishlist_default = defineTool3({
  name: "list_wishlist",
  title: "List wishlist entries",
  description: "List community-submitted wishlist entries (mie ayam outlets pending review). Filter by status. Pending/rejected entries require admin privileges via RLS.",
  inputSchema: {
    status: z3.enum(["pending", "approved", "rejected"]).default("approved").describe("Wishlist status filter."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    const { data, error } = await supabaseForUser(ctx).from("wishlist_entries").select("id, place_name, location, notes, status, created_at").eq("status", status).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { entries: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-wishlist.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^4.4.3";
var submit_wishlist_default = defineTool4({
  name: "submit_wishlist",
  title: "Submit a mie ayam outlet to the wishlist",
  description: "Submit a new mie ayam outlet recommendation to the wishlist. Entry starts with status 'pending' and needs admin approval before appearing publicly.",
  inputSchema: {
    place_name: z4.string().min(1).describe("Name of the mie ayam outlet."),
    location: z4.string().min(1).describe("City / address / area of the outlet."),
    notes: z4.string().optional().describe("Why this outlet is worth reviewing (optional).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ place_name, location, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("wishlist_entries").insert({ place_name, location, notes: notes ?? null, status: "pending" }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Wishlist entry submitted (pending review). ID: ${data.id}` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/tools/moderate-wishlist.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^4.4.3";
var moderate_wishlist_default = defineTool5({
  name: "moderate_wishlist",
  title: "Approve or reject a wishlist entry (admin)",
  description: "Set the status of a wishlist entry to 'approved' or 'rejected'. Requires admin privileges; RLS will reject non-admin callers.",
  inputSchema: {
    id: z5.string().uuid().describe("Wishlist entry ID."),
    status: z5.enum(["approved", "rejected"]).describe("New status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("wishlist_entries").update({ status }).eq("id", id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Wishlist entry ${id} set to '${status}'.` }],
      structuredContent: { entry: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kqsqocrtaybbkpigvwjy";
var mcp_default = defineMcp({
  name: "mie-ayam-ranger-mcp",
  title: "Mie Ayam Ranger",
  version: "0.1.0",
  instructions: "Tools for Mie Ayam Ranger \u2014 a directory of Indonesian mie ayam outlet reviews. Use `search_reviews` and `get_review` to explore the review database. Use `list_wishlist` to see community-submitted outlet suggestions, `submit_wishlist` to add a new one, and `moderate_wishlist` (admin only) to approve/reject entries.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_reviews_default, get_review_default, list_wishlist_default, submit_wishlist_default, moderate_wishlist_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
